# fly.toml app configuration file generated for forum-flow on 2023-06-19T10:24:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "forum-flow"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
